[versions]
agp = "8.13.2"
kotlin = "2.3.0"
annotation = "1.9.1"
# Compose
composeBom = "2026.02.00"
navigationCompose = "2.9.7"
lifecycleViewmodelCompose = "2.8.7"
activityCompose = "1.12.4"
capsule = "2.1.3"
material3 = "1.5.0-alpha14"



[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
# Compose
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
capsule = { module = "io.github.kyant0:capsule", version.ref = "capsule" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

